### ISSUE TITLE
How is it possible to install the package with no connection to github.com

### ISSUE THREAD

**Issue by hauntedhill** [SAP/cloud-mta#216]
Hello,

i try to install the package in an environment without direct internet connection. The access to github.com is not directly possible. 

Because of that is it possible to provide the neccesarry binaries manually to install mta successfully? 

Or is it possible to replace github.com uri by configuration with a different url to provide the binaries?

For example:

`https://github.com/SAP/cloud-mta/releases/download/v${version}/cloud-mta_${version}_`;

replace with:

`https://my-own-url/SAP/cloud-mta/releases/download/v${version}/cloud-mta_${version}_`;

Thanks and Regards

Haunted

**Comment by michawai** [comment]
Not supported
