### ISSUE TITLE
Writing MTA yaml file is removing comments and re-writing the file.

### ISSUE THREAD

**Issue by ianquigley-sap** [SAP/cloud-mta#217]
Do you want to request a feature or report a bug?

- Please search existing issues to avoid creating duplicates. https://github.com/SAP/cloud-mta/releases. 
- Also please test using the `latest` version build to make sure your issue has not already been fixed: 

Please provide the following info:

  - Library version: Latest
  - OS Version: Windows or Linux
  - If possible, provide a link to the project:  https://www.npmjs.com/package/@sap/generator-fiori

Steps to Reproduce:

1.  Using the Fiori generator linked above, the MTA yaml is updated using this library.  All the comments, space lines etc. have been removed and same content has be reordered

Is it possible to have a version of the library that doesn't replace and order in this way?

**Comment by katunin-ng** [comment]
HI @ianquigley-sap,
Such lib version is not available and due to missing tools with good support for the expected behavior in yaml in general currently, we are not planning to support it either.
Regards
Natalia
